title: Pablo's Portfolio
description: Hi, I'm Pablo Sanchez, a computer engineer from Spain. I'm interested in programming, electronics and cybersecurity.
author: Pablo Sanchez
email: pablosanchez2002@gmail.com
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
plugins:
- jekyll-feed
- jekyll-youtube